import { Campaign, DailyProgress, ActivityUpdate } from './types';

// Extended Mock Data for all features
import type { CampaignSubmission } from './types';

// ============ RBAC - CLIENTS & TEAM ============
export interface ClientData {
  id: string;
  name: string;
  industry: string;
  campaignManager: string;
  backupManager: string;
  campaignStatus: 'Active' | 'Paused' | 'Completed';
  leadsUploaded: number;
  lastActivity: string;
  activeCampaigns: number;
}

export const mockClients: ClientData[] = [
  {
    id: 'client_1',
    name: 'The Channel Company',
    industry: 'Information Technology',
    campaignManager: 'Brijesh Singh',
    backupManager: 'Arjun Patel',
    campaignStatus: 'Active',
    leadsUploaded: 1594,
    lastActivity: '2 hours ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_2',
    name: 'TechCo Ltd',
    industry: 'SaaS',
    campaignManager: 'Brijesh Singh',
    backupManager: 'Arjun Patel',
    campaignStatus: 'Active',
    leadsUploaded: 2108,
    lastActivity: '1 day ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_3',
    name: 'Meridian Group',
    industry: 'Financial Services',
    campaignManager: 'Brijesh Singh',
    backupManager: 'Arjun Patel',
    campaignStatus: 'Active',
    leadsUploaded: 893,
    lastActivity: '3 hours ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_4',
    name: 'Global Innovations Inc',
    industry: 'Manufacturing',
    campaignManager: 'Michael Chen',
    backupManager: 'Emily Rodriguez',
    campaignStatus: 'Active',
    leadsUploaded: 1087,
    lastActivity: '5 hours ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_5',
    name: 'Nexus Enterprises',
    industry: 'Healthcare',
    campaignManager: 'Emily Rodriguez',
    backupManager: 'Michael Chen',
    campaignStatus: 'Active',
    leadsUploaded: 1742,
    lastActivity: '1 day ago',
    activeCampaigns: 2,
  },
];

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: 'Campaign Manager' | 'Campaign Backup' | 'Operations Manager';
  assignedClients: string[];
  activeCampaigns: number;
  clientsAssigned: number;
  status: 'Active' | 'Away';
  avatar?: string;
}

/**
 * Team members can also be deactivated. The base `TeamMember` status stays
 * narrow because the seeded roster only ever contains active/away people;
 * this widened record is what the management screen and its modals pass
 * around once deactivation is in play.
 */
export type TeamMemberRecord = Omit<TeamMember, 'status'> & {
  status: TeamMember['status'] | 'Inactive';
};

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm_1',
    name: 'Brijesh Singh',
    email: 'brijesh.singh@datamaticsbpm.com',
    phone: '+91 22 4040 1234',
    role: 'Campaign Manager',
    assignedClients: ['The Channel Company', 'TechCo Ltd', 'Meridian Group'],
    activeCampaigns: 7,
    clientsAssigned: 3,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_2',
    name: 'Michael Chen',
    email: 'michael.chen@datamaticsbpm.com',
    phone: '+1 415-555-0142',
    role: 'Campaign Manager',
    assignedClients: ['Global Innovations Inc', 'Nexus Enterprises'],
    activeCampaigns: 4,
    clientsAssigned: 2,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@datamaticsbpm.com',
    phone: '+1 212-555-0198',
    role: 'Campaign Manager',
    assignedClients: ['Nexus Enterprises', 'Global Innovations Inc'],
    activeCampaigns: 3,
    clientsAssigned: 2,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_4',
    name: 'Arjun Patel',
    email: 'arjun.patel@datamaticsbpm.com',
    phone: '+91 22 4040 5678',
    role: 'Campaign Backup',
    assignedClients: ['The Channel Company', 'TechCo Ltd', 'Meridian Group'],
    activeCampaigns: 5,
    clientsAssigned: 3,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_5',
    name: 'Praful Sanil',
    email: 'praful.sanil@datamaticsbpm.com',
    phone: '+91 22 4040 9012',
    role: 'Operations Manager',
    assignedClients: [],
    activeCampaigns: 14,
    clientsAssigned: 0,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
];

// Mock CSV preview data for Lead Upload Modal
export const mockCsvPreview = [
  {
    'First Name': 'Robert',
    'Last Name': 'Chen',
    'Email': 'robert.chen@northgateitp.com',
    'Phone': '+1 415-555-1234',
    'Company': 'Northgate IT Partners',
    'Job Title': 'Chief Information Security Officer',
    'Source': 'LinkedIn',
  },
  {
    'First Name': 'Jennifer',
    'Last Name': 'Martinez',
    'Email': 'j.martinez@globalfinance.com',
    'Phone': '+1 212-555-5678',
    'Company': 'Global Finance Corp',
    'Job Title': 'IT Director',
    'Source': 'Conference',
  },
  {
    'First Name': 'David',
    'Last Name': 'Kim',
    'Email': 'd.kim@healthcaresolutions.com',
    'Phone': '+1 617-555-9012',
    'Company': 'Healthcare Solutions Ltd',
    'Job Title': 'Security Manager',
    'Source': 'Webinar',
  },
  {
    'First Name': 'Emma',
    'Last Name': 'Thompson',
    'Email': 'e.thompson@londonbanking.co.uk',
    'Phone': '+44 20 7123 4567',
    'Company': 'London Banking Group',
    'Job Title': 'CFO',
    'Source': 'Partner Referral',
  },
  {
    'First Name': 'Michael',
    'Last Name': 'Anderson',
    'Email': 'm.anderson@techsolutions.com',
    'Phone': '+1 555-123-4567',
    'Company': 'Tech Solutions LLC',
    'Job Title': 'VP of Technology',
    'Source': 'Email Campaign',
  },
];

// ============ CAMPAIGNS ============
// 17 campaigns across 5 companies — mixed geographies, types, statuses, pricing, progress
export const mockCampaigns: Campaign[] = [

  // ── The Channel Company — 3 live campaigns (seeded from live data, Jul 2026) ──
  // Numbers are the client's own and must not be adjusted. accepted === delivered
  // by design for this demo so no delivered-vs-billable gap is shown.
  {
    id: '46888',
    name: 'Lenovo Intel FIFA AI',
    clientCompany: 'The Channel Company',
    serviceType: 'Content Syndication',
    status: 'In progress',
    startDate: 'Jun 7, 2026',
    endDate: 'Oct 31, 2026',
    delivered: 314,
    target: 350,
    accepted: 314,
    lastUpdated: 'Jul 28, 2026',
    geo: 'NAM',
    industry: 'Information Technology',
    revenueRange: '$50M+',
    employeeSize: '500+',
    jobTitles: 'IT Director, VP IT, CIO, CTO',
    pricingModel: 'CPL',
    clientDetails: {
      name: 'The Channel Company',
      address: '350 Jericho Turnpike | Ste 310, Jericho, NY 11753',
      contact: 'Renuka Lawless',
    },
    scopeOfWork: ['Content syndication', 'Lead validation & QA', 'Weekly delivery reporting'],
    terms: 'Net 30',
  },
  {
    id: '46873',
    name: 'Uptime Solutions CRN2 - Lead Gen',
    clientCompany: 'The Channel Company',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: 'May 25, 2026',
    endDate: 'Aug 31, 2026',
    delivered: 59,
    target: 80,
    accepted: 59,
    lastUpdated: 'Jul 28, 2026',
    geo: 'NAM',
    industry: 'Information Technology',
    revenueRange: '$10M+',
    employeeSize: '200+',
    jobTitles: 'IT Manager, Infrastructure Lead, DevOps Manager',
    pricingModel: 'CPL',
    clientDetails: {
      name: 'The Channel Company',
      address: '350 Jericho Turnpike | Ste 310, Jericho, NY 11753',
      contact: 'Renuka Lawless',
    },
    scopeOfWork: ['Lead generation', 'Lead validation & QA', 'Weekly delivery reporting'],
    terms: 'Net 30',
  },
  {
    id: '46936',
    name: 'Eaton 2026 Full Year 1_Q3',
    clientCompany: 'The Channel Company',
    serviceType: 'Content Syndication',
    status: 'In progress',
    startDate: 'Jun 29, 2026',
    endDate: 'Sep 30, 2026',
    delivered: 41,
    target: 100,
    accepted: 41,
    lastUpdated: 'Jul 27, 2026',
    geo: 'NAM',
    industry: 'Manufacturing & Energy',
    revenueRange: '$50M+',
    employeeSize: '1,000+',
    jobTitles: 'Facilities Director, VP Operations, Data Center Manager',
    pricingModel: 'CPL',
    clientDetails: {
      name: 'The Channel Company',
      address: '350 Jericho Turnpike | Ste 310, Jericho, NY 11753',
      contact: 'Renuka Lawless',
    },
    scopeOfWork: ['Content syndication', 'Lead validation & QA', 'Weekly delivery reporting'],
    terms: 'Net 30',
  },

  // ── TechCo Ltd (SaaS) — 4 campaigns ────────────────────────────────────────
  {
    id: '4',
    name: 'Enterprise Outreach – North America Q1 2026',
    clientCompany: 'TechCo Ltd',
    serviceType: 'Double Touch',
    status: 'In progress',
    startDate: '2026-01-08',
    endDate: '2026-04-15',
    delivered: 1203,
    target: 1500,
    accepted: 915,
    lastUpdated: '2026-03-02',
    geo: 'North America (US)',
    industry: 'Software, SaaS, Cloud',
    revenueRange: '$10M – $200M',
    employeeSize: '100 – 2,000',
    jobTitles: 'VP Sales, VP Marketing, Director of Revenue, CRO',
    pricingModel: 'Per lead ($42/lead)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'Two-touch email sequence targeting SaaS revenue leaders',
      'Personalised subject lines using company and title data',
      'Weekly batch delivery of 300 contacts per cycle',
      'Monthly optimisation review call included',
    ],
    terms: 'Payment terms: Net 30. Double-touch sequence must complete before lead is counted.',
  },
  {
    id: '5',
    name: 'SMB SaaS Decision Makers – EMEA 2025–26',
    clientCompany: 'TechCo Ltd',
    serviceType: 'Leads',
    status: 'Completed',
    startDate: '2025-11-01',
    endDate: '2026-02-28',
    delivered: 905,
    target: 800,
    accepted: 624,
    lastUpdated: '2026-02-28',
    geo: 'EMEA (UK, Germany, Netherlands, France, Sweden)',
    industry: 'Software, E-commerce, Professional Services',
    revenueRange: '$5M – $100M',
    employeeSize: '50 – 1,000',
    jobTitles: 'CEO, COO, Head of Operations, IT Manager, Procurement Manager',
    pricingModel: 'Per lead ($38/lead)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'Generate GDPR-compliant SMB leads across 5 EMEA markets',
      'Localised outreach in English, German, French where required',
      'Quarterly batch delivery schedule with suppression applied',
      'Client suppression list applied before each delivery',
    ],
    terms: 'Payment terms: Net 30. GDPR-compliant opt-in required on every lead. Overage at $38 CPL.',
  },
  {
    id: '6',
    name: 'APAC SaaS Appointment Setting – Q2 2026',
    clientCompany: 'TechCo Ltd',
    serviceType: 'Appointment Setting',
    status: 'Not started',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    delivered: 0,
    target: 80,
    accepted: 0,
    lastUpdated: '2026-02-28',
    geo: 'Asia Pacific (Singapore, Australia, Japan)',
    industry: 'Technology, SaaS, Cloud Infrastructure',
    revenueRange: '$20M – $500M',
    employeeSize: '200 – 5,000',
    jobTitles: 'CTO, VP Product, Head of Engineering, Director of IT',
    pricingModel: 'Per appointment ($220/appointment)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'Set qualified discovery calls with APAC technology leaders',
      'Confirm each appointment 48 hours in advance',
      'Provide 1-page prospect brief before each meeting',
      'Reschedule no-shows free of charge within campaign window',
    ],
    terms: 'Payment terms: Net 30. Campaign kickoff scheduled Apr 1, 2026. Job card awaiting final signature.',
  },
  {
    id: '6b',
    name: 'EMEA Financial Services BANT – Q2 2026',
    clientCompany: 'TechCo Ltd',
    serviceType: 'BANT',
    status: 'Pending Approval',
    startDate: '2026-05-01',
    endDate: '2026-07-31',
    delivered: 0,
    target: 150,
    accepted: 0,
    lastUpdated: '2026-02-28',
    geo: 'EMEA (UK, Germany, France, Netherlands, Sweden)',
    industry: 'Financial Services, Banking',
    revenueRange: '$500M+',
    employeeSize: '1,000+',
    jobTitles: 'CFO, Head of Finance, VP Financial Operations, Chief Risk Officer',
    pricingModel: 'Per qualified lead ($120/lead)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'BANT-qualify financial services leaders across 5 EMEA markets',
      'Confirm budget authority and purchase timeline on every lead',
      'English, German, French phone interviews as required',
      'Deliver qualification notes with each accepted lead',
    ],
    terms: 'Campaign pending approval by campaign manager. Projected launch May 2026.',
  },

  // ── Meridian Group (Financial Services) — 4 campaigns ─────────────────────
  {
    id: '7',
    name: 'UK Banking Sector BANT – Q1 2026',
    clientCompany: 'Meridian Group',
    serviceType: 'BANT',
    status: 'In progress',
    startDate: '2025-12-01',
    endDate: '2026-03-31',
    delivered: 412,
    target: 500,
    accepted: 305,
    lastUpdated: '2026-03-01',
    geo: 'EMEA (United Kingdom)',
    industry: 'Banking, Financial Services',
    revenueRange: '$250M+',
    employeeSize: '1,000+',
    jobTitles: 'CFO, Head of Digital Banking, Innovation Director, CRO',
    pricingModel: 'Per qualified lead ($125/lead)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'Qualify leads through BANT framework (Budget, Authority, Need, Timeline)',
      'Phone interviews to confirm all 4 BANT criteria',
      'Document qualification notes and pain points per lead',
      'Deliver only fully qualified opportunities in fortnightly batches',
    ],
    terms: 'Payment terms: Net 45. All 4 BANT criteria must be confirmed. Sample review required before bulk delivery.',
  },
  {
    id: '8',
    name: 'FinTech Decision Makers – DACH Region',
    clientCompany: 'Meridian Group',
    serviceType: 'Leads',
    status: 'Paused',
    startDate: '2026-01-15',
    endDate: '2026-04-30',
    delivered: 245,
    target: 400,
    accepted: 162,
    lastUpdated: '2026-02-10',
    geo: 'EMEA (Germany, Austria, Switzerland)',
    industry: 'Financial Technology, Insurance, Wealth Management',
    revenueRange: '$100M – $1B',
    employeeSize: '500 – 5,000',
    jobTitles: 'CTO, CDO, VP Digital Transformation, Head of Payments',
    pricingModel: 'Per lead ($68/lead)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'German-language outreach to FinTech decision-makers in DACH',
      'Bi-weekly batch delivery of 125 leads per cycle',
      'Translate and localise all contact touchpoints',
      'Apply client suppression list before every batch',
    ],
    terms: 'Payment terms: Net 30. Campaign paused Feb 10 — awaiting revised targeting confirmation from client.',
  },
  {
    id: '9',
    name: 'APAC CloudTech Appointment Setting Program',
    clientCompany: 'Meridian Group',
    serviceType: 'Appointment Setting',
    status: 'In progress',
    startDate: '2026-03-01',
    endDate: '2026-05-31',
    delivered: 22,
    target: 60,
    accepted: 18,
    lastUpdated: '2026-03-01',
    geo: 'Asia Pacific (Singapore, Australia, India, Japan)',
    industry: 'Technology, Cloud Computing',
    revenueRange: '$50M – $500M',
    employeeSize: '500 – 2,000',
    jobTitles: 'CTO, VP Technology, Head of Cloud Infrastructure, DevOps Director',
    pricingModel: 'Per appointment ($200/appointment)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'Set confirmed discovery appointments with APAC cloud leaders',
      'Confirm bookings 24 hours in advance of each meeting',
      'Provide detailed prospect brief and tech stack summary',
      'Reschedule no-shows within the same campaign window',
    ],
    terms: 'Payment terms: Net 30. Only attended appointments billed. Briefing notes 1 hour before each call.',
  },
  {
    id: '9b',
    name: 'Nordic FinTech Leads – Single Touch Q2 2026',
    clientCompany: 'Meridian Group',
    serviceType: 'Single Touch',
    status: 'Changes Requested',
    startDate: '2026-05-01',
    endDate: '2026-07-31',
    delivered: 0,
    target: 250,
    accepted: 0,
    lastUpdated: '2026-02-26',
    geo: 'EMEA (Sweden, Norway, Denmark, Finland)',
    industry: 'Financial Technology, Banking, Insurance',
    revenueRange: '$50M – $500M',
    employeeSize: '200 – 2,000',
    jobTitles: 'CTO, Head of Digital Banking, VP Innovation, Director of Payments',
    pricingModel: 'Per lead ($58/lead)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'Single touch outreach to Nordic FinTech leaders',
      'English and Swedish language outreach versions',
      'GDPR-compliant opt-in on all contacts',
      'Monthly delivery of 85 leads per batch',
    ],
    terms: 'Campaign under review. Changes requested by campaign manager — awaiting client response.',
  },

  // ── Global Innovations Inc (Manufacturing) — 4 campaigns ───────────────────
  {
    id: '10',
    name: 'Manufacturing Leads – North America Q1 2026',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-01-20',
    endDate: '2026-04-20',
    delivered: 623,
    target: 700,
    accepted: 486,
    lastUpdated: '2026-03-02',
    geo: 'North America (US, Canada)',
    industry: 'Manufacturing, Industrial Automation, Heavy Equipment',
    revenueRange: '$50M – $500M',
    employeeSize: '500 – 5,000',
    jobTitles: 'VP Operations, Plant Manager, Automation Director, Head of Procurement',
    pricingModel: 'Per lead ($55/lead)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'Generate leads for industrial automation solutions across North America',
      'Multi-touch verification of all contacts before delivery',
      'Bi-weekly batch delivery of 175 leads per cycle',
      'Account-based targeting for Fortune 1000 manufacturers',
    ],
    terms: 'Payment terms: Net 30. Leads valid for 30 days from delivery. Replacement within 10 business days.',
  },
  {
    id: '11',
    name: 'EMEA Industrial Automation – Double Touch',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'Double Touch',
    status: 'In progress',
    startDate: '2026-02-15',
    endDate: '2026-05-15',
    delivered: 228,
    target: 500,
    accepted: 162,
    lastUpdated: '2026-02-28',
    geo: 'EMEA (Germany, France, Italy, Spain, Netherlands)',
    industry: 'Manufacturing, Automotive, Aerospace',
    revenueRange: '$100M – $2B',
    employeeSize: '1,000 – 10,000',
    jobTitles: 'VP Manufacturing, Plant Director, Head of Industry 4.0, CTO',
    pricingModel: 'Per lead ($72/lead)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'Two-touch outreach to European manufacturing decision-makers',
      'Localised content for German, French, Italian audiences',
      'Bi-weekly delivery of 125 leads per batch',
      'Industry 4.0 and smart factory vertical focus',
    ],
    terms: 'Payment terms: Net 30. GDPR-compliant data required on all European leads.',
  },
  {
    id: '12',
    name: 'Global Supply Chain Leaders – Content Syndication Q3 2025',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'Content Syndication',
    status: 'Completed',
    startDate: '2025-09-01',
    endDate: '2025-12-15',
    delivered: 780,
    target: 750,
    accepted: 694,
    lastUpdated: '2025-12-15',
    geo: 'Global (US, UK, Germany, Singapore, Australia)',
    industry: 'Manufacturing, Logistics, Supply Chain',
    revenueRange: '$100M+',
    employeeSize: '1,000+',
    jobTitles: 'Chief Supply Chain Officer, VP Logistics, Head of Procurement, COO',
    pricingModel: 'Per download ($42/download)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'Distribute Supply Chain Resilience 2025 industry report',
      'Multi-market distribution across 5 key global regions',
      'Verified opt-in download tracking throughout',
      'CRM-ready lead file delivered monthly with all metadata',
    ],
    terms: 'Payment terms: Net 30. Final delivery completed Dec 15, 2025. Overage billed at $42 CPD.',
  },
  {
    id: '12b',
    name: 'APAC Manufacturing BANT – Q2 2026',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'BANT',
    status: 'Pending Approval',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    delivered: 0,
    target: 120,
    accepted: 0,
    lastUpdated: '2026-02-27',
    geo: 'Asia Pacific (Japan, South Korea, Singapore, Taiwan)',
    industry: 'Electronics Manufacturing, Semiconductor, Automotive',
    revenueRange: '$200M+',
    employeeSize: '2,000+',
    jobTitles: 'Chief Manufacturing Officer, SVP Operations, Factory Director, Head of Automation',
    pricingModel: 'Per qualified lead ($140/lead)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'BANT-qualify manufacturing decision-makers in East Asia',
      'English and Japanese-language phone interviews',
      'Confirm active budget cycle and purchasing timeline',
      'Deliver fully qualified leads with detailed qualification notes',
    ],
    terms: 'Campaign pending approval. Projected start: Apr 1, 2026. Awaiting campaign manager sign-off.',
  },

  // ── Nexus Enterprises (Healthcare) — 4 campaigns ───────────────────────────
  {
    id: '13',
    name: 'Healthcare Provider Campaign – Q4 2025',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'Leads',
    status: 'Completed',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    delivered: 892,
    target: 900,
    accepted: 785,
    lastUpdated: '2025-12-31',
    geo: 'United States',
    industry: 'Healthcare, Hospital Networks, Medical Devices',
    revenueRange: '$100M+',
    employeeSize: '1,000+',
    jobTitles: 'Chief Medical Officer, VP Healthcare IT, Clinical Director, CIO',
    pricingModel: 'Per lead ($60/lead)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'Generate qualified healthcare decision-maker leads',
      'HIPAA-compliant data handling throughout campaign lifecycle',
      'Quarterly batch delivery with full verification',
      '100% replacement guarantee for invalid contacts within 14 days',
    ],
    terms: 'Payment terms: Net 30. HIPAA BAA signed prior to campaign start.',
  },
  {
    id: '14',
    name: 'Medical Device Decision Makers – US 2026',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-01-10',
    endDate: '2026-04-30',
    delivered: 520,
    target: 750,
    accepted: 442,
    lastUpdated: '2026-03-02',
    geo: 'United States',
    industry: 'Medical Devices, MedTech, Diagnostics',
    revenueRange: '$50M – $1B',
    employeeSize: '500 – 10,000',
    jobTitles: 'VP Medical Affairs, Head of Clinical, Director of Regulatory Affairs, CMO',
    pricingModel: 'Per lead ($58/lead)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'Generate MedTech decision-maker leads for diagnostic solutions',
      'HIPAA-compliant contact verification throughout',
      'Bi-weekly delivery of 175 leads per batch',
      'Filter for companies with active procurement cycles only',
    ],
    terms: 'Payment terms: Net 30. HIPAA compliance required. Invalid leads replaced within 10 business days.',
  },
  {
    id: '15',
    name: 'Healthcare IT BANT Qualification – EMEA 2026',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'BANT',
    status: 'In progress',
    startDate: '2026-02-01',
    endDate: '2026-05-31',
    delivered: 180,
    target: 300,
    accepted: 142,
    lastUpdated: '2026-03-01',
    geo: 'EMEA (UK, Germany, Netherlands, France, Nordics)',
    industry: 'Healthcare IT, Digital Health, Hospital Management Systems',
    revenueRange: '$100M+',
    employeeSize: '500+',
    jobTitles: 'CIO, CDO, Head of Digital Health, VP Healthcare Technology',
    pricingModel: 'Per qualified lead ($130/lead)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'BANT-qualify healthcare IT decision-makers across EMEA',
      'Confirm digital health initiative budget and timeline',
      'Phone interviews in English, German, French as required',
      'Deliver detailed qualification notes with each approved lead',
    ],
    terms: 'Payment terms: Net 45. Full BANT required. GDPR consent captured on all European leads.',
  },
  {
    id: '16',
    name: 'APAC MedTech Content Syndication – Q2 2026',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'Content Syndication',
    status: 'Pending Approval',
    startDate: '2026-04-15',
    endDate: '2026-07-15',
    delivered: 0,
    target: 400,
    accepted: 0,
    lastUpdated: '2026-03-01',
    geo: 'Asia Pacific (Japan, Australia, Singapore, South Korea)',
    industry: 'Healthcare, MedTech, Pharmaceuticals',
    revenueRange: '$50M+',
    employeeSize: '500+',
    jobTitles: 'VP Healthcare IT, Head of Digital Medicine, CTO, Clinical Director',
    pricingModel: 'Per download ($45/download)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'Distribute Nexus 2026 APAC Healthcare Technology Report',
      'APAC privacy regulation compliance (PDPA, PIPL, Australian Privacy Act)',
      'Bi-monthly delivery of 200 download leads per batch',
      'English and Japanese localised content versions',
    ],
    terms: 'Campaign pending approval by campaign manager. Job card to be issued upon approval.',
  },
];

// ─── Campaign Approval Workflow — Mock Submissions ────────────────────────────
export const mockCampaignSubmissions: CampaignSubmission[] = [
  // ── Pending Approval ────────────────────────────────────────────────────────
  {
    id: 'sub_001',
    campaignName: 'AI-Powered SaaS Lead Generation Q2 2026',
    clientId: 'client_2',
    clientCompany: 'TechCo Ltd',
    submittedBy: 'Sarah Johnson',
    submittedAt: '2026-03-01T09:30:00Z',
    assignedManager: 'Brijesh Singh',
    assignedManagerEmail: 'brijesh.singh@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'Leads',
    geography: 'North America',
    locations: ['California', 'New York', 'Texas', 'Illinois', 'Washington'],
    targetLeads: 400,
    cpl: 55,
    jobTitles: ['CTO', 'VP Engineering', 'Director of AI', 'Head of Data Science', 'VP Product'],
    employeeSize: '500 – 5,000',
    industry: 'Software / SaaS',
    additionalInfo: 'Focus on companies that have raised Series B or later. Prefer leads from companies actively deploying AI infrastructure in production.',
  },
  {
    id: 'sub_002',
    campaignName: 'EMEA Financial Services BANT Q2 2026',
    clientId: 'client_2',
    clientCompany: 'TechCo Ltd',
    submittedBy: 'James Whitfield',
    submittedAt: '2026-02-28T14:45:00Z',
    assignedManager: 'Brijesh Singh',
    assignedManagerEmail: 'brijesh.singh@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'BANT',
    geography: 'EMEA',
    locations: ['United Kingdom', 'Germany', 'France', 'Netherlands', 'Sweden'],
    targetLeads: 150,
    cpl: 120,
    jobTitles: ['CFO', 'Head of Finance', 'VP Financial Operations', 'Chief Risk Officer'],
    employeeSize: '1,000+',
    industry: 'Financial Services / Banking',
    additionalInfo: 'BANT qualification required on all leads. Budget authority must be confirmed. Purchasing timeline: within 6 months.',
  },
  {
    id: 'sub_005',
    campaignName: 'APAC Manufacturing BANT – Q2 2026',
    clientId: 'client_4',
    clientCompany: 'Global Innovations Inc',
    submittedBy: 'Rachel Huang',
    submittedAt: '2026-02-27T10:15:00Z',
    assignedManager: 'Michael Chen',
    assignedManagerEmail: 'michael.chen@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'BANT',
    geography: 'APAC',
    locations: ['Japan', 'South Korea', 'Singapore', 'Taiwan'],
    targetLeads: 120,
    cpl: 140,
    jobTitles: ['Chief Manufacturing Officer', 'SVP Operations', 'Factory Director', 'Head of Automation'],
    employeeSize: '2,000+',
    industry: 'Electronics Manufacturing / Semiconductor / Automotive',
    additionalInfo: 'Looking for decision-makers with active capex budgets for manufacturing automation. Japanese-language interviews required for Japan contacts.',
  },
  {
    id: 'sub_006',
    campaignName: 'APAC MedTech Content Syndication – Q2 2026',
    clientId: 'client_5',
    clientCompany: 'Nexus Enterprises',
    submittedBy: 'Dr. Priya Nair',
    submittedAt: '2026-03-01T07:45:00Z',
    assignedManager: 'Emily Rodriguez',
    assignedManagerEmail: 'emily.rodriguez@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'Content Syndication',
    geography: 'APAC',
    locations: ['Japan', 'Australia', 'Singapore', 'South Korea'],
    targetLeads: 400,
    cpl: 45,
    jobTitles: ['VP Healthcare IT', 'Head of Digital Medicine', 'CTO', 'Clinical Director'],
    employeeSize: '500+',
    industry: 'Healthcare / MedTech / Pharmaceuticals',
    additionalInfo: 'Distribution of our 2026 APAC Healthcare AI report. All contacts must be PDPA/PIPL compliant. Japanese and English versions available.',
  },
  // ── Changes Requested ───────────────────────────────────────────────────────
  {
    id: 'sub_003',
    campaignName: 'Healthcare IT Director Content Syndication',
    clientId: 'client_2',
    clientCompany: 'TechCo Ltd',
    submittedBy: 'Sarah Johnson',
    submittedAt: '2026-02-25T11:00:00Z',
    assignedManager: 'Brijesh Singh',
    assignedManagerEmail: 'brijesh.singh@datamaticsbpm.com',
    status: 'Changes Requested',
    serviceType: 'Content Syndication',
    geography: 'North America',
    locations: ['United States'],
    targetLeads: 300,
    cpl: 38,
    jobTitles: ['CIO', 'IT Director', 'VP Healthcare IT', 'Director of Clinical Informatics'],
    employeeSize: '200 – 5,000',
    industry: 'Healthcare / Medical Devices',
    additionalInfo: 'Distribute our Q1 Healthcare AI white paper. Need HIPAA-compliant contacts only.',
    managerNotes: 'The target of 300 leads at $38 CPL is below our capacity threshold for this niche vertical. We can deliver 200 leads at $42 CPL confidently, or 300 at $46 CPL. Please confirm your preference. Also please share the white paper asset so our compliance team can verify content before we begin distribution.',
    reviewedAt: '2026-02-26T09:15:00Z',
    reviewedBy: 'Brijesh Singh',
  },
  {
    id: 'sub_007',
    campaignName: 'Nordic FinTech Leads – Single Touch Q2 2026',
    clientId: 'client_3',
    clientCompany: 'Meridian Group',
    submittedBy: 'David Okafor',
    submittedAt: '2026-02-24T13:30:00Z',
    assignedManager: 'Brijesh Singh',
    assignedManagerEmail: 'brijesh.singh@datamaticsbpm.com',
    status: 'Changes Requested',
    serviceType: 'Single Touch',
    geography: 'EMEA',
    locations: ['Sweden', 'Norway', 'Denmark', 'Finland'],
    targetLeads: 250,
    cpl: 58,
    jobTitles: ['CTO', 'Head of Digital Banking', 'VP Innovation', 'Director of Payments'],
    employeeSize: '200 – 2,000',
    industry: 'Financial Technology / Banking / Insurance',
    additionalInfo: 'Need English and Swedish outreach. All leads must be GDPR opt-in. Focus on challenger banks and digital-first insurers.',
    managerNotes: 'Nordic FinTech is a tight vertical — the 250-lead target at $58 CPL may take 5–6 months at current market capacity. Recommend starting with 150 leads over 3 months to validate quality, then scaling. Also clarify: do you want Swedish-language outreach for all 4 markets, or just Sweden?',
    reviewedAt: '2026-02-25T10:00:00Z',
    reviewedBy: 'Brijesh Singh',
  },
  // ── Approved ────────────────────────────────────────────────────────────────
  {
    id: 'sub_004',
    campaignName: 'APAC CloudTech Appointment Setting Program',
    clientId: 'client_3',
    clientCompany: 'Meridian Group',
    submittedBy: 'David Okafor',
    submittedAt: '2026-02-20T08:00:00Z',
    assignedManager: 'Brijesh Singh',
    assignedManagerEmail: 'brijesh.singh@datamaticsbpm.com',
    status: 'Approved',
    serviceType: 'Appointment Setting',
    geography: 'APAC',
    locations: ['Singapore', 'Australia', 'Japan', 'India'],
    targetLeads: 60,
    cpl: 200,
    jobTitles: ['CTO', 'VP Technology', 'Head of Cloud Infrastructure', 'DevOps Director'],
    employeeSize: '500 – 2,000',
    industry: 'Technology / Cloud Computing',
    reviewedAt: '2026-02-21T10:30:00Z',
    reviewedBy: 'Brijesh Singh',
  },
  {
    id: 'sub_008',
    campaignName: 'North America Enterprise SaaS – Double Touch Q1 2026',
    clientId: 'client_2',
    clientCompany: 'TechCo Ltd',
    submittedBy: 'James Whitfield',
    submittedAt: '2025-12-18T09:00:00Z',
    assignedManager: 'Brijesh Singh',
    assignedManagerEmail: 'brijesh.singh@datamaticsbpm.com',
    status: 'Approved',
    serviceType: 'Double Touch',
    geography: 'North America',
    locations: ['United States'],
    targetLeads: 1500,
    cpl: 42,
    jobTitles: ['VP Sales', 'VP Marketing', 'Director of Revenue', 'CRO', 'Head of Growth'],
    employeeSize: '100 – 2,000',
    industry: 'Software / SaaS / Cloud',
    reviewedAt: '2025-12-20T14:00:00Z',
    reviewedBy: 'Brijesh Singh',
  },
  // ── Declined ────────────────────────────────────────────────────────────────
  {
    id: 'sub_009',
    campaignName: 'Global C-Suite Outreach – Custom Program',
    clientId: 'client_3',
    clientCompany: 'Meridian Group',
    submittedBy: 'John Smith',
    submittedAt: '2026-02-10T10:00:00Z',
    assignedManager: 'Brijesh Singh',
    assignedManagerEmail: 'brijesh.singh@datamaticsbpm.com',
    status: 'Declined',
    serviceType: 'Custom',
    geography: 'Global',
    locations: ['United States', 'United Kingdom', 'Germany', 'Singapore', 'Australia', 'Japan'],
    targetLeads: 50,
    cpl: 350,
    jobTitles: ['CEO', 'President', 'Chairman'],
    employeeSize: '5,000+',
    industry: 'All Industries',
    additionalInfo: 'Looking for C-Suite only — CEO/President level. Needs to be warm intros, not cold outreach.',
    managerNotes: 'This campaign profile is outside our current service capability. We do not offer warm introduction programs at the C-Suite/CEO level across 6 global markets. Our existing services cover BANT qualification and appointment setting up to VP level. Recommend scoping a more targeted BANT campaign for SVP/VP decision-makers instead.',
    reviewedAt: '2026-02-12T11:00:00Z',
    reviewedBy: 'Brijesh Singh',
  },
];

export function getPendingSubmissions(): CampaignSubmission[] {
  return mockCampaignSubmissions.filter(s => s.status === 'Pending Approval');
}

export function getSubmissionsNeedingAttention(): CampaignSubmission[] {
  return mockCampaignSubmissions.filter(
    s => s.status === 'Pending Approval' || s.status === 'Changes Requested'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

export const mockDailyProgress: DailyProgress[] = [
  { date: '2026-02-24', leadsSourced: 45, leadsValidated: 38, leadsRejected: 7, bantQualified: 32, appointmentsSet: 2 },
  { date: '2026-02-25', leadsSourced: 52, leadsValidated: 44, leadsRejected: 8, bantQualified: 38, appointmentsSet: 3 },
  { date: '2026-02-26', leadsSourced: 48, leadsValidated: 41, leadsRejected: 7, bantQualified: 35, appointmentsSet: 2 },
  { date: '2026-02-27', leadsSourced: 50, leadsValidated: 43, leadsRejected: 7, bantQualified: 37, appointmentsSet: 3 },
];

export const mockActivityUpdates: ActivityUpdate[] = [
  { title: 'RFP received from client', message: 'RFP received from client', date: '2026-01-05', timestamp: 'Jan 5, 2026', completed: true },
  { title: 'Job card signed by client', message: 'Job card signed by client', date: '2026-01-12', timestamp: 'Jan 12, 2026', completed: true },
  { title: 'Campaign started', message: 'Campaign started — lead generation in progress', date: '2026-01-15', timestamp: 'Jan 15, 2026', completed: true },
  { title: 'First batch delivered (150 leads)', message: 'First batch delivered — 150 leads sent for review', date: '2026-02-03', timestamp: 'Feb 3, 2026', completed: true },
  { title: 'Second batch delivered (150 leads)', message: 'Second batch delivered — 150 leads sent for review', date: '2026-02-06', timestamp: 'Feb 6, 2026', completed: true },
  { title: 'Third batch delivered (150 leads)', message: 'Third batch delivered — 150 leads sent for review', date: '2026-02-10', timestamp: 'Feb 10, 2026', completed: true },
  { title: 'Fourth batch delivered (150 leads)', message: 'Fourth batch delivered — 150 leads sent for review', date: '2026-02-13', timestamp: 'Feb 13, 2026', completed: true },
  { title: 'Fifth batch delivered (80 leads)', message: 'Fifth batch delivered — 80 leads sent for review', date: '2026-02-17', timestamp: 'Feb 17, 2026', completed: true },
  { title: 'Campaign milestone: 68% complete', message: 'Campaign has reached 68% completion — 680 of 1,000 leads delivered', date: '2026-02-20', timestamp: 'Feb 20, 2026', completed: true },
  { title: 'Next batch scheduled', message: 'Next delivery scheduled for Mar 3, 2026 — 150 leads expected', date: '2026-03-01', timestamp: '2 days ago', completed: false },
];

// ============ LEADS ============
export interface Lead {
  id: string;
  campaignId: string;
  campaignName: string;
  firstName: string;
  lastName: string;
  title: string;
  company: string;
  industry: string;
  email: string;
  phone: string;
  country: string;
  employeeSize: string;
  revenue: string;
  leadScore: number;
  status: 'Pending Review' | 'Accepted' | 'Rejected' | 'Contacted';
  deliveryDate: string;
  rejectionReason?: string;
  notes?: string;
}

export const mockLeads: Lead[] = [
  // Channel-industry ICP: MSPs, VARs, solution providers, security resellers
  // and distributors. People are fictional; every lead belongs to one of the
  // three seeded TCC campaigns and carries a positive or neutral status.
  {
    id: 'L001',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Marcus',
    lastName: 'Whitfield',
    title: 'IT Director',
    company: 'Summit Managed Services',
    industry: 'Information Technology',
    email: 'm.whitfield@summitmsp.com',
    phone: '+1 617-555-1007',
    country: 'United States',
    employeeSize: '500 – 1,000',
    revenue: '$68M',
    leadScore: 96,
    status: 'Accepted',
    deliveryDate: '2026-07-20',
  },
  {
    id: 'L002',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Priya',
    lastName: 'Raghavan',
    title: 'VP IT',
    company: 'Northgate IT Partners',
    industry: 'Information Technology',
    email: 'p.raghavan@northgateitp.com',
    phone: '+1 617-555-1014',
    country: 'United States',
    employeeSize: '1,000 – 2,500',
    revenue: '$140M',
    leadScore: 94,
    status: 'Accepted',
    deliveryDate: '2026-07-20',
  },
  {
    id: 'L003',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Daniel',
    lastName: 'Okonkwo',
    title: 'CIO',
    company: 'ClearPath Solutions Group',
    industry: 'Information Technology',
    email: 'd.okonkwo@clearpathsg.com',
    phone: '+1 617-555-1021',
    country: 'United States',
    employeeSize: '2,000 – 5,000',
    revenue: '$310M',
    leadScore: 92,
    status: 'Accepted',
    deliveryDate: '2026-07-21',
  },
  {
    id: 'L004',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Hannah',
    lastName: 'Lindqvist',
    title: 'CTO',
    company: 'Beacon Technology Group',
    industry: 'Information Technology',
    email: 'h.lindqvist@beacontechgrp.com',
    phone: '+1 617-555-1028',
    country: 'United States',
    employeeSize: '500 – 1,000',
    revenue: '$74M',
    leadScore: 91,
    status: 'Accepted',
    deliveryDate: '2026-07-21',
  },
  {
    id: 'L005',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Reuben',
    lastName: 'Castellanos',
    title: 'IT Director',
    company: 'Ironwood Systems Integration',
    industry: 'Information Technology',
    email: 'r.castellanos@ironwoodsi.com',
    phone: '+1 617-555-1035',
    country: 'United States',
    employeeSize: '800 – 1,500',
    revenue: '$96M',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-07-22',
  },
  {
    id: 'L006',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Alicia',
    lastName: 'Mbeki',
    title: 'VP IT',
    company: 'Cascade Network Solutions',
    industry: 'Information Technology',
    email: 'a.mbeki@cascadenet.com',
    phone: '+1 416-555-1042',
    country: 'Canada',
    employeeSize: '600 – 1,200',
    revenue: '$82M',
    leadScore: 87,
    status: 'Contacted',
    deliveryDate: '2026-07-22',
  },
  {
    id: 'L007',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Tobias',
    lastName: 'Renner',
    title: 'IT Director',
    company: 'Silverline Technology Partners',
    industry: 'Information Technology',
    email: 't.renner@silverlinetp.com',
    phone: '+1 617-555-1049',
    country: 'United States',
    employeeSize: '500 – 900',
    revenue: '$59M',
    leadScore: 85,
    status: 'Accepted',
    deliveryDate: '2026-07-23',
  },
  {
    id: 'L008',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Naomi',
    lastName: 'Fairbanks',
    title: 'CTO',
    company: 'Vantage Point Integrators',
    industry: 'Information Technology',
    email: 'n.fairbanks@vantagepointint.com',
    phone: '+1 617-555-1056',
    country: 'United States',
    employeeSize: '700 – 1,400',
    revenue: '$88M',
    leadScore: 83,
    status: 'Pending Review',
    deliveryDate: '2026-07-23',
  },
  {
    id: 'L009',
    campaignId: '46888',
    campaignName: 'Lenovo Intel FIFA AI',
    firstName: 'Elias',
    lastName: 'Thornbury',
    title: 'VP IT',
    company: 'Copperfield IT Services',
    industry: 'Information Technology',
    email: 'e.thornbury@copperfieldits.com',
    phone: '+1 617-555-1063',
    country: 'United States',
    employeeSize: '550 – 1,000',
    revenue: '$61M',
    leadScore: 79,
    status: 'Pending Review',
    deliveryDate: '2026-07-24',
  },
  {
    id: 'L010',
    campaignId: '46873',
    campaignName: 'Uptime Solutions CRN2 - Lead Gen',
    firstName: 'Sonia',
    lastName: 'Vasquez',
    title: 'Infrastructure Lead',
    company: 'Lakeshore Managed IT',
    industry: 'Information Technology',
    email: 's.vasquez@lakeshoremit.com',
    phone: '+1 617-555-1070',
    country: 'United States',
    employeeSize: '200 – 500',
    revenue: '$24M',
    leadScore: 93,
    status: 'Accepted',
    deliveryDate: '2026-07-20',
  },
  {
    id: 'L011',
    campaignId: '46873',
    campaignName: 'Uptime Solutions CRN2 - Lead Gen',
    firstName: 'Cormac',
    lastName: 'Delaney',
    title: 'DevOps Manager',
    company: 'Halcyon Cloud Partners',
    industry: 'Information Technology',
    email: 'c.delaney@halcyoncloud.com',
    phone: '+1 617-555-1077',
    country: 'United States',
    employeeSize: '250 – 600',
    revenue: '$31M',
    leadScore: 90,
    status: 'Accepted',
    deliveryDate: '2026-07-21',
  },
  {
    id: 'L012',
    campaignId: '46873',
    campaignName: 'Uptime Solutions CRN2 - Lead Gen',
    firstName: 'Imani',
    lastName: 'Brooks',
    title: 'IT Manager',
    company: 'Blue Harbor Solution Providers',
    industry: 'Information Technology',
    email: 'i.brooks@blueharborsp.com',
    phone: '+1 617-555-1084',
    country: 'United States',
    employeeSize: '200 – 450',
    revenue: '$18M',
    leadScore: 86,
    status: 'Accepted',
    deliveryDate: '2026-07-22',
  },
  {
    id: 'L013',
    campaignId: '46873',
    campaignName: 'Uptime Solutions CRN2 - Lead Gen',
    firstName: 'Viktor',
    lastName: 'Almeida',
    title: 'Infrastructure Lead',
    company: 'Waypoint Infrastructure Group',
    industry: 'Information Technology',
    email: 'v.almeida@waypointig.com',
    phone: '+1 617-555-1091',
    country: 'United States',
    employeeSize: '300 – 700',
    revenue: '$37M',
    leadScore: 84,
    status: 'Contacted',
    deliveryDate: '2026-07-23',
  },
  {
    id: 'L014',
    campaignId: '46873',
    campaignName: 'Uptime Solutions CRN2 - Lead Gen',
    firstName: 'Freya',
    lastName: 'Nakamura',
    title: 'DevOps Manager',
    company: 'Granite Peak Technologies',
    industry: 'Information Technology',
    email: 'f.nakamura@granitepeaktech.com',
    phone: '+1 416-555-1098',
    country: 'Canada',
    employeeSize: '220 – 500',
    revenue: '$21M',
    leadScore: 82,
    status: 'Accepted',
    deliveryDate: '2026-07-24',
  },
  {
    id: 'L015',
    campaignId: '46873',
    campaignName: 'Uptime Solutions CRN2 - Lead Gen',
    firstName: 'Desmond',
    lastName: 'Achterberg',
    title: 'IT Manager',
    company: 'Kestrel Security Resellers',
    industry: 'Information Technology',
    email: 'd.achterberg@kestrelsec.com',
    phone: '+1 617-555-1105',
    country: 'United States',
    employeeSize: '200 – 400',
    revenue: '$16M',
    leadScore: 77,
    status: 'Pending Review',
    deliveryDate: '2026-07-24',
  },
  {
    id: 'L016',
    campaignId: '46936',
    campaignName: 'Eaton 2026 Full Year 1_Q3',
    firstName: 'Rosalind',
    lastName: 'Ferraro',
    title: 'Data Center Manager',
    company: 'Ridgeline Data Centers',
    industry: 'Manufacturing & Energy',
    email: 'r.ferraro@ridgelinedc.com',
    phone: '+1 617-555-1112',
    country: 'United States',
    employeeSize: '1,000 – 3,000',
    revenue: '$220M',
    leadScore: 95,
    status: 'Accepted',
    deliveryDate: '2026-07-21',
  },
  {
    id: 'L017',
    campaignId: '46936',
    campaignName: 'Eaton 2026 Full Year 1_Q3',
    firstName: 'Anselm',
    lastName: 'Kowalczyk',
    title: 'VP Operations',
    company: 'Arbor Industrial Systems',
    industry: 'Manufacturing & Energy',
    email: 'a.kowalczyk@arborindustrial.com',
    phone: '+1 617-555-1119',
    country: 'United States',
    employeeSize: '1,500 – 4,000',
    revenue: '$390M',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-07-22',
  },
  {
    id: 'L018',
    campaignId: '46936',
    campaignName: 'Eaton 2026 Full Year 1_Q3',
    firstName: 'Petra',
    lastName: 'Simonsen',
    title: 'Facilities Director',
    company: 'Trailhead Energy Solutions',
    industry: 'Manufacturing & Energy',
    email: 'p.simonsen@trailheadenergy.com',
    phone: '+1 617-555-1126',
    country: 'United States',
    employeeSize: '1,200 – 2,500',
    revenue: '$180M',
    leadScore: 84,
    status: 'Contacted',
    deliveryDate: '2026-07-23',
  },
  {
    id: 'L019',
    campaignId: '46936',
    campaignName: 'Eaton 2026 Full Year 1_Q3',
    firstName: 'Gideon',
    lastName: 'Marchetti',
    title: 'Data Center Manager',
    company: 'Stonebridge Technology Distributors',
    industry: 'Manufacturing & Energy',
    email: 'g.marchetti@stonebridgetd.com',
    phone: '+1 617-555-1133',
    country: 'United States',
    employeeSize: '1,000 – 2,000',
    revenue: '$155M',
    leadScore: 81,
    status: 'Accepted',
    deliveryDate: '2026-07-24',
  },
  {
    id: 'L020',
    campaignId: '46936',
    campaignName: 'Eaton 2026 Full Year 1_Q3',
    firstName: 'Yolanda',
    lastName: 'Prescott',
    title: 'VP Operations',
    company: 'Redpoint Distribution Partners',
    industry: 'Manufacturing & Energy',
    email: 'y.prescott@redpointdp.com',
    phone: '+1 416-555-1140',
    country: 'Canada',
    employeeSize: '1,100 – 2,200',
    revenue: '$168M',
    leadScore: 76,
    status: 'Pending Review',
    deliveryDate: '2026-07-24',
  },
];
