// ─── Computable insights ─────────────────────────────────────────────────────
// Rules that turn the campaign selectors into the one-line callouts rendered by
// InsightStrip. The hard constraint, and the reason this file is small and
// boring on purpose: every rule must state something the chart above it already
// proves. No recommendations, no budget advice, no "consider shifting spend" —
// those are opinions, and an opinion generated by a threshold is worse than no
// opinion at all.
//
// Practical test for adding a rule here: if a client screenshotted the strip
// and the chart together, would the two agree without further explanation? If
// not, it doesn't belong.

import type { Insight } from '../components/ui/InsightStrip';
import {
  getAccountFunnel, getAudienceOverlap, getBuyingCentre, getChannelPerformance,
  getFrequencyDistribution, getUnreachedAccounts,
} from './propensity';
import { getAssetPerformance, getLeadQuality } from './syndicationPerformance';

export function getReachInsights(abmCampaignId: string): Insight[] {
  const funnel = getAccountFunnel(abmCampaignId);
  if (funnel.length === 0) return [];
  const out: Insight[] = [];

  const unreached = getUnreachedAccounts(abmCampaignId);
  if (unreached.total > 0) {
    out.push({
      id: 'unreached',
      tone: 'watch',
      text: `${unreached.total} of the ${funnel[0].accounts} named accounts have not been served a single impression yet.`,
    });
  }

  const overlap = getAudienceOverlap(abmCampaignId);
  const single = overlap[0];
  if (single && single.percentage >= 40) {
    out.push({
      id: 'single-channel',
      tone: 'neutral',
      text: `${single.percentage}% of reached accounts have only been touched on one channel.`,
    });
  }

  const salesReady = funnel[4];
  if (salesReady && salesReady.accounts > 0) {
    out.push({
      id: 'sales-ready',
      tone: 'good',
      text: `${salesReady.accounts} accounts are showing hot warmth right now, ${salesReady.pctOfTargeted}% of the target list.`,
    });
  }
  return out;
}

export function getAudienceInsights(abmCampaignId: string): Insight[] {
  const centre = getBuyingCentre(abmCampaignId);
  if (!centre) return [];
  const out: Insight[] = [];

  out.push({
    id: 'seniority',
    tone: centre.directorPlusPct >= 55 ? 'good' : 'neutral',
    text: `${centre.directorPlusPct}% of the people reached sit at Director level or above.`,
  });

  // Under three stakeholders means we are reaching individuals, not committees.
  out.push({
    id: 'depth',
    tone: centre.avgPerAccount >= 4 ? 'good' : 'watch',
    text: `${centre.avgPerAccount} stakeholders reached per engaged account, across ${centre.stakeholders.toLocaleString('en-US')} people in total.`,
  });
  return out;
}

export function getAdvertisingInsights(abmCampaignId: string): Insight[] {
  const out: Insight[] = [];

  const bands = getFrequencyDistribution(abmCampaignId);
  const total = bands.reduce((s, b) => s + b.accounts, 0);
  const sweet = bands.find(b => b.inSweetSpot);
  if (sweet && total > 0) {
    out.push({
      id: 'frequency',
      tone: 'neutral',
      text: `${Math.round((sweet.accounts / total) * 100)}% of reached accounts sit in the 7 to 12 impression band, where engagement peaks before fatigue.`,
    });
  }

  const overExposed = bands.filter(b => b.band === '19+').reduce((s, b) => s + b.accounts, 0);
  if (total > 0 && overExposed / total >= 0.1) {
    out.push({
      id: 'over-exposed',
      tone: 'watch',
      text: `${overExposed} accounts have seen 19 or more impressions.`,
    });
  }

  const channels = getChannelPerformance(abmCampaignId);
  const best = [...channels].sort((a, b) => b.ctr - a.ctr)[0];
  if (best) {
    out.push({
      id: 'best-channel',
      tone: 'good',
      text: `${best.channel} is returning the highest click-through rate at ${best.ctr}%.`,
    });
  }
  return out;
}

export function getDeliveryInsights(campaignId: string, totalLeads: number): Insight[] {
  if (totalLeads <= 0) return [];
  const out: Insight[] = [];

  const assets = getAssetPerformance(campaignId, totalLeads);
  if (assets.length > 1) {
    const byRate = [...assets].sort((a, b) => b.conversionRate - a.conversionRate);
    const top = byRate[0];
    const bottom = byRate[byRate.length - 1];
    out.push({
      id: 'best-asset',
      tone: 'good',
      text: `"${top.name}" converts at ${top.conversionRate}%, against ${bottom.conversionRate}% for the lowest performer.`,
    });
  }

  const quality = getLeadQuality(campaignId, totalLeads);
  if (quality && quality.rejected > 0) {
    out.push({
      id: 'replaced',
      tone: 'neutral',
      text: `${quality.rejected} leads were rejected and all ${quality.replaced} have been replaced at no charge.`,
    });
  }
  return out;
}
